# Site settings
title: Laurent Thiebault - Software Engineer
description: eat(); sleep(); code(); repeat();
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Laurent Thiebault
user_description: "Currently in 2nd year of MIAGE Master alternating with Norsys as a software developer, I am thirsty for learning and sharing!
Indeed, passionate about IT, I like to keep abreast of new developments in the field, whether technical (languages, methods and work environment) or leisure (innovation, general public, hi-tech).
Young, dynamic and voluntary, I love to live my passion by participating in innovative projects while sharing my knowledge."

user_title: Software Developer

# Google-analytics
google-analytics:
  id: "UA-114409076-1"

exclude: ['package.json', 'src' , 'node_modules']
